In [25]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [45]:

data = pd.read_csv("/home/admin1/Downloads/zoo_data(For Decision Tree Program).csv")
data

1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...   
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1   
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0   
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0   
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0   

    1.7  
0     1  
1     4  
2     1  
3     1  
4     1  
..  ...  
95    1  
96    6  
97    1  
98    7  
99    2  

[100 rows x 17 columns]

In [46]:
data.head()

1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0  1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1  0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2  1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4  1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   

   1.7  
0    1  
1    4  
2    1  
3    1  
4    1

In [55]:
y=data["1.7"]
#x=data.drop(columns=["1.7"])

In [56]:
#x

In [57]:
import numpy as np
y=np.array(y)
print(y)

[1 4 1 1 1 1 4 4 1 1 2 4 7 7 7 2 1 4 1 2 2 1 2 6 5 5 1 1 1 6 1 1 2 4 1 1 2
 4 6 6 2 6 2 1 1 7 1 1 1 1 6 5 7 1 1 2 2 2 2 4 4 3 1 1 1 1 1 1 1 1 2 7 4 1
 1 3 7 2 2 3 7 4 2 1 7 4 2 6 5 3 3 4 1 1 2 1 6 1 7 2]


In [58]:
x=np.array(x)
print(x)

[[1 0 0 ... 1 0 1]
 [0 0 1 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]]


In [59]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 


In [60]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)


In [61]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.9666666666666667
